apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: app-test
  annotations:
    risk/score: "0.0"
spec:
  replicas: 2
  selector: { matchLabels: { app: demo-app } }
  template:
    metadata: { labels: { app: demo-app } }
    spec:
      securityContext: { runAsNonRoot: true, runAsUser: 1000 }
      containers:
        - name: app
          image: ghcr.io/hamzi-o/devsecops-as-code/app:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          livenessProbe: { httpGet: { path: /healthz, port: 8080 }, initialDelaySeconds: 5 }
          readinessProbe: { httpGet: { path: /healthz, port: 8080 }, initialDelaySeconds: 5 }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "512Mi" }
