apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: demo-app
        image: ghcr.io/hamzi-o/devsecops/app:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: / # Assuming your app has a root endpoint that returns 200 OK when ready
            port: 8080
          initialDelaySeconds: 10 # Give the app some time to start
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: / # Assuming your app has a root endpoint that returns 200 OK when healthy
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
