apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  namespace: app-test
spec:
  selector:
    app: demo-app
  ports:
    - name: http
      port: 80          # exposed to cluster/ingress
      targetPort: 8080  # container port
  type: ClusterIP
