apiVersion: batch/v1
kind: Job
metadata:
  name: zap-scan
  namespace: app-test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: zap
          image: zaproxy/zap-stable
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              # Read the target URL from ConfigMap
              TARGET_URL=staging.hamza-builds.info
              echo "Scanning target: $TARGET_URL"
              
              # Run ZAP spider and active scan
              zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true
              sleep 10
              zap-cli --zap-url http://localhost:8080 status -t 120
              zap-cli --zap-url http://localhost:8080 spider $TARGET_URL
              zap-cli --zap-url http://localhost:8080 active-scan $TARGET_URL
              zap-cli --zap-url http://localhost:8080 report -o /zap/wrk/zap-report.json -f json
              zap-cli --zap-url http://localhost:8080 report -o /zap/wrk/zap-report.html -f html
          volumeMounts:
            - name: zap-config
              mountPath: /zap-config
            - name: zap-work
              mountPath: /zap/wrk
      volumes:
        - name: zap-config
          configMap:
            name: zap-config
        - name: zap-work
          emptyDir: {}
