apiVersion: batch/v1
kind: Job
metadata:
  name: zap-scan
  namespace: app-test
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: zap
    spec:
      restartPolicy: Never
      containers:
      - name: zap
        image: zaproxy/zap-stable
        command:
          - /bin/sh
          - -c
          - |
            set -e
            TARGET=http://staging.hamza-builds.info/
            #OPTIONS=$(cat /zap-config/zap-options)

            echo "Starting ZAP full scan for $TARGET with options $OPTIONS"
            mkdir -p /zap/wrk

            zap-full-scan.py \
              -t "$TARGET" \
              -r /zap/wrk/zap-report.html \
              -J /zap/wrk/zap-report.json \
              -a || true

        volumeMounts:
        - name: zap-reports
          mountPath: /zap/wrk
      volumes:
      - name: zap-reports
        emptyDir: {}
