apiVersion: batch/v1
kind: Job
metadata:
  name: zap-scan
  namespace: app-test
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: zap
          image: ghcr.io/zaproxy/zaproxy:2.15.0
          command:
            - /bin/sh
            - -c
            - |
              TARGET=$(cat /zap-config/target-url)
              zap-baseline.py \
                -t "$TARGET" \
                -r /zap/wrk/zap-report.html \
                -J /zap/wrk/zap-report.json \
                -z "-config globalexcludeurl.url_list.url.regex=.*logout.* -config globalexcludeurl.url_list.url.enabled=true"
          volumeMounts:
            - name: zap-config
              mountPath: /zap-config
            - name: zap-reports
              mountPath: /zap/wrk
      volumes:
        - name: zap-config
          configMap:
            name: zap-config
        - name: zap-reports
          emptyDir: {}
