apiVersion: batch/v1
kind: Job
metadata:
  name: zap-scan
  namespace: app-test
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: zap
    spec:
      restartPolicy: Never
      containers:
      - name: zap
        image: zaproxy/zap-stable
        command:
          - /bin/sh
          - -c
          - |
            set -e
            TARGET=$(cat /zap-config/target-url)
            CONFIG_FILE=/zap-config/zap_config.yml
            OPTIONS=$(cat /zap-config/zap-options)

            echo "Starting ZAP baseline scan for $TARGET with config $CONFIG_FILE and options $OPTIONS"
            mkdir -p /zap/wrk

            zap-baseline.py \
              -t "$TARGET" \
              -c "$CONFIG_FILE" \
              $OPTIONS \
              -r /zap/wrk/zap-report.html \
              -J /zap/wrk/zap-report.json

            echo "ZAP scan completed. Reports are stored in /zap/wrk/"
        volumeMounts:
        - name: zap-config
          mountPath: /zap-config
        - name: zap-reports
          mountPath: /zap/wrk
      volumes:
      - name: zap-config
        configMap:
          name: zap-config
      - name: zap-reports
        emptyDir: {}
