apiVersion: batch/v1
kind: Job
metadata:
  name: zap-scan
  namespace: app-test
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: zap
    spec:
      restartPolicy: Never
      containers:
      - name: zap
        image: zaproxy/zap-stable
        command:
          - /bin/sh
          - -c
          - |
            TARGET=$(cat /zap-config/target-url)
            OPTIONS=$(cat /zap-config/zap-options)
            echo "Starting ZAP baseline scan for $TARGET with options: $OPTIONS"

            # Ensure output directory exists
            mkdir -p /zap/wrk

            # Copy config file to work dir
            cp scanners/zap_config.yml /zap/wrk/config/zap_config.yml

            # Run ZAP baseline scan
            zap-baseline.py -t "$TARGET" -c /zap/wrk/config/zap_config.yml -r /zap/wrk/zap-report.html -j /zap/wrk/zap-report.json $OPTIONS

            echo "ZAP scan completed. Reports saved in /zap/wrk/"
        volumeMounts:
        - name: zap-config
          mountPath: /zap-config
        - name: zap-reports
          mountPath: /zap/wrk
      volumes:
      - name: zap-config
        configMap:
          name: zap-config
      - name: zap-reports
        emptyDir: {}
