apiVersion: batch/v1
kind: Job
metadata:
  name: zap-scan
  namespace: app-test
spec:
  template:
    spec:
      containers:
      - name: zap
        image: zaproxy/zap-stable # Updated ZAP image
        command: ["/bin/sh", "-c"]
        args: [
          "TARGET=$(cat /zap/wrk/target-url ); \
          zap-baseline.py \
          -t \"$TARGET\" \
          -r /zap/wrk/zap-report.html \
          -J /zap/wrk/zap-report.json \
          -z \"-config globalexcludeurl.url_list.url.regex=.*logout.* -config globalexcludeurl.url_list.url.enabled=true\""
        ]
        volumeMounts:
        - name: zap-config-volume
          mountPath: /zap/wrk/config
        - name: zap-target-volume
          mountPath: /zap/wrk/target-url
          subPath: target-url
        - name: zap-report-volume
          mountPath: /zap/wrk
      restartPolicy: Never
      volumes:
      - name: zap-config-volume
        configMap:
          name: zap-config
          items:
          - key: zap-options
            path: zap_config.yml
      - name: zap-target-volume
        configMap:
          name: zap-config
          items:
          - key: target-url
            path: target-url
      - name: zap-report-volume
        emptyDir: {}
  backoffLimit: 0
