apiVersion: batch/v1
kind: Job
metadata:
  name: zap-scan
  namespace: app-test
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: zap
    spec:
      restartPolicy: Never
      containers:
      - name: zap
        image: zaproxy/zap-stable
        command:
          - /bin/sh
          - -c
          - |
            set -e
            TARGET=http://staging.hamza-builds.info/

            echo "Starting ZAP full scan for $TARGET"
            mkdir -p /zap/wrk

            zap-full-scan.py \
              -t "$TARGET" \
              -r /zap/wrk/zap-report.html \
              -J /zap/wrk/zap-report.json || true

            echo "=== Preview of ZAP JSON report ==="
            head -n 50 /zap/wrk/zap-report.json || echo "No JSON report found"

            echo "=== Preview of ZAP HTML report ==="
            head -n 50 /zap/wrk/zap-report.html || echo "No HTML report found"

            # 🔴 Keep container alive for 5 minutes so GitHub can kubectl cp
            echo "Sleeping to allow report copy..."
            sleep 300

        volumeMounts:
        - name: zap-reports
          mountPath: /zap/wrk
      volumes:
      - name: zap-reports
        emptyDir: {}
